import { Invoice } from '@kirana-pro/shared';

export const DASHBOARD_INVOICES: Invoice[] = [
  {
    id: 'inv_101',
    invoiceNumber: 'INV-2026-0042',
    storeId: 'demo_store_1',
    items: [
      {
        productId: 'prod_1',
        name: 'Aashirvaad Shudh Chakki Atta 5kg',
        unit: 'packet',
        isLoose: false,
        quantity: 1,
        unitPrice: 250,
        discount: 0,
        gstRate: 0,
        taxableAmount: 250,
        gstAmount: 0,
        totalAmount: 250,
        hsnCode: '1101',
      },
      {
        productId: 'prod_2',
        name: 'Tata Salt Vacuum Evaporated 1kg',
        unit: 'packet',
        isLoose: false,
        quantity: 2,
        unitPrice: 28,
        discount: 0,
        gstRate: 0,
        taxableAmount: 56,
        gstAmount: 0,
        totalAmount: 56,
        hsnCode: '2501',
      },
    ],
    subtotal: 306,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 306,
    paymentMode: 'cash',
    paymentStatus: 'paid',
    amountPaid: 306,
    amountDue: 0,
    cashTendered: 500,
    changeDue: 194,
    counterNumber: 1,
    staffName: 'Ramu Cashier',
    createdAt: '2026-10-05T09:30:00.000Z',
    createdBy: 'demo_owner',
  },
  {
    id: 'inv_102',
    invoiceNumber: 'INV-2026-0043',
    storeId: 'demo_store_1',
    items: [
      {
        productId: 'prod_3',
        name: 'Loose Basmati Chawal (Premium)',
        unit: 'kg',
        isLoose: true,
        quantity: 2.5,
        unitPrice: 50,
        discount: 0,
        gstRate: 0,
        taxableAmount: 125,
        gstAmount: 0,
        totalAmount: 125,
        hsnCode: '1006',
      },
      {
        productId: 'prod_5',
        name: 'Maggi 2-Minute Masala Noodles 70g',
        unit: 'packet',
        isLoose: false,
        quantity: 4,
        unitPrice: 14,
        discount: 0,
        gstRate: 12,
        taxableAmount: 50,
        gstAmount: 6,
        totalAmount: 56,
        hsnCode: '1902',
      },
    ],
    subtotal: 175,
    discountTotal: 0,
    taxTotal: 6,
    grandTotal: 181,
    paymentMode: 'upi',
    paymentStatus: 'paid',
    amountPaid: 181,
    amountDue: 0,
    counterNumber: 1,
    staffName: 'Ramu Cashier',
    createdAt: '2026-10-05T10:15:00.000Z',
    createdBy: 'demo_owner',
  },
  {
    id: 'inv_103',
    invoiceNumber: 'INV-2026-0044',
    storeId: 'demo_store_1',
    customer: {
      id: 'cust_demo_1',
      name: 'Ramesh Sharma (Pandit Ji)',
      phoneNumber: '9876543210',
    },
    items: [
      {
        productId: 'prod_6',
        name: 'Fortune Sunlite Refined Sunflower Oil 1L',
        unit: 'packet',
        isLoose: false,
        quantity: 2,
        unitPrice: 145,
        discount: 10,
        gstRate: 5,
        taxableAmount: 266.67,
        gstAmount: 13.33,
        totalAmount: 280,
        hsnCode: '1512',
      },
    ],
    subtotal: 266.67,
    discountTotal: 10,
    taxTotal: 13.33,
    grandTotal: 280,
    paymentMode: 'credit',
    paymentStatus: 'unpaid',
    amountPaid: 0,
    amountDue: 280,
    counterNumber: 2,
    staffName: 'Suresh Kumar',
    createdAt: '2026-10-05T11:45:00.000Z',
    createdBy: 'demo_owner',
  },
  {
    id: 'inv_104',
    invoiceNumber: 'INV-2026-0045',
    storeId: 'demo_store_1',
    customer: {
      id: 'cust_b2b_1',
      name: 'Aggarwal Caterers & Sweets',
      phoneNumber: '9811223344',
    },
    isB2B: true,
    customerGstin: '07AAACA1234A1Z5',
    items: [
      {
        productId: 'prod_1',
        name: 'Aashirvaad Shudh Chakki Atta 5kg',
        unit: 'packet',
        isLoose: false,
        quantity: 10,
        unitPrice: 250,
        discount: 100,
        gstRate: 0,
        taxableAmount: 2400,
        gstAmount: 0,
        totalAmount: 2400,
        hsnCode: '1101',
      },
      {
        productId: 'prod_6',
        name: 'Fortune Sunlite Refined Sunflower Oil 1L',
        unit: 'packet',
        isLoose: false,
        quantity: 15,
        unitPrice: 145,
        discount: 75,
        gstRate: 5,
        taxableAmount: 2000,
        gstAmount: 100,
        totalAmount: 2100,
        hsnCode: '1512',
      },
      {
        productId: 'prod_5',
        name: 'Maggi 2-Minute Masala Noodles 70g',
        unit: 'packet',
        isLoose: false,
        quantity: 50,
        unitPrice: 14,
        discount: 50,
        gstRate: 12,
        taxableAmount: 580.36,
        gstAmount: 69.64,
        totalAmount: 650,
        hsnCode: '1902',
      },
    ],
    subtotal: 4980.36,
    discountTotal: 225,
    taxTotal: 169.64,
    grandTotal: 5150,
    paymentMode: 'upi',
    paymentStatus: 'paid',
    amountPaid: 5150,
    amountDue: 0,
    counterNumber: 1,
    staffName: 'Ramu Cashier',
    createdAt: '2026-10-05T14:20:00.000Z',
    createdBy: 'demo_owner',
  },
  {
    id: 'inv_105',
    invoiceNumber: 'INV-2026-0046',
    storeId: 'demo_store_1',
    customer: {
      id: 'cust_b2b_2',
      name: 'Gupta Sweets & Chai Stall',
      phoneNumber: '9899112233',
    },
    isB2B: true,
    customerGstin: '07BBBPG5678B1Z2',
    items: [
      {
        productId: 'prod_4',
        name: 'Loose Shakar Cheeni (Pure Sugar)',
        unit: 'kg',
        isLoose: true,
        quantity: 50,
        unitPrice: 42,
        discount: 50,
        gstRate: 5,
        taxableAmount: 1952.38,
        gstAmount: 97.62,
        totalAmount: 2050,
        hsnCode: '1701',
      },
    ],
    subtotal: 1952.38,
    discountTotal: 50,
    taxTotal: 97.62,
    grandTotal: 2050,
    paymentMode: 'cash',
    paymentStatus: 'paid',
    amountPaid: 2050,
    amountDue: 0,
    counterNumber: 1,
    staffName: 'Ramu Cashier',
    createdAt: '2026-10-06T09:10:00.000Z',
    createdBy: 'demo_owner',
  },
];
